### ISSUE TITLE
Python import error

### ISSUE THREAD

**Issue by adefelicibus** [peterjc/galaxy_mira#1]
Hi, I've installed this tool from Galaxy [Tool Shed](http://toolshed.g2.bx.psu.edu/view/peterjc/mira4_assembler) on our Galaxy instance and got this error:
`from mira4_make_bam import make_bam
`

How can I install this package on my environment?

**Comment by peterjc** [comment]
Do you have the complete error message? When do you see the error message - when trying to run the tool?

Can you confirm which version from the tool shed you have? e.g. revision a4f602cc3aa9 which is the currently the latest on the main Tool Shed?

Also which version of Galaxy do you have?

**Comment by adefelicibus** [comment]
@peterjc We are using Galaxy with Pulsar and this error appers when the job runs on a Pulsar client.
The complete error message is:
`Traceback (most recent call last):
File '/usr/share/pulsar/files/staging/1915/tool_files/mira4.py', line 13, in <module>
    from mira4_make_bam import make_bam
ImportError: No module named mira4_make_bam`

When the job runs local, we don't get this error.
Maybe this is a problem between Galaxy and Pulsar, and not with the tool.

The revision of the tool is the last, a4f602cc3aa9. And the version of Galaxy is 16.01 with Pulsar 0.6.1.

**Comment by peterjc** [comment]
Hmm. This `from mira4_make_bam import make_bam` line is in the main wrapper script `mira4.py`, which wants to import a function from the sister file `mira4_make_bam.py` which ought to be in the same directory.

My guess is the staging folder `/usr/share/pulsar/files/staging/1915/tool_files/` does not have the second python file? If the folder still exists, can you list the contents? @jmchilton can probably guide us on how to debug this further as I've not used pulsar myself.

If you need an urgent hack, then you can remove the `from mira4_make_bam import make_bam` line and instead copy in at least the `depad` and and `make_bam` functions from `mira4_make_bam.py`  into `mira4.py` - do you know enough Python to try that without further guidance? But I want to stress, this is just a short term hack!

**Comment by jmchilton** [comment]
Pulsar doesn't know how to see the required files that need to be transferred - tool authors need to be able to mark these up in the tool XML but it is currently not implemented (https://github.com/galaxyproject/galaxy/issues/1609). This is urgent and is something I will do this summer I think - but probably not until after the ISMB.

I'd say the behavior of this tool is just such that it will not work with Pulsar at this time.

A work around might be to download the tool tarball and untar somewhere (`/path/to/mira_tarball_extract`) on the remote server and create a pulsar destination just for this tool which hacks up PYTHONPATH:

```
<destination id="mira_over_pulsar" runner="pulsar">
   ...
   <env id="PYTHONPATH">/path/to/mira_tarball_extract</env>
</destination>
```

**Comment by peterjc** [comment]
I'm going to close this as due to a bug in Pulsar, filed as https://github.com/galaxyproject/pulsar/issues/113

(I have no objection to this MIRA wrapper issue being used to record possible workarounds though)

**Comment by adefelicibus** [comment]
Thank you @peterjc  and @jmchilton.
I'll wait the new features from Galaxy and Pulsar, until that the tool will run locally.
