### ISSUE TITLE
Conda support

### ISSUE THREAD

**Issue by lecorguille** [peterjc/galaxy_mira#2]
Hi Peter,

Just a little Issues to track the Conda support developments. 
No rush!

https://github.com/peterjc/galaxy_mira/blob/master/tools/mira4_0/mira4.py#L72 waits for `$MIRA` defined in the tool_dependency but for sur not in Conda path.
```python
try:
    mira_path = os.environ["MIRA4"]
except KeyError:
    sys.exit("Environment variable $MIRA4 not set")
```

Can you just consider that mira is in the `$PATH` or is there specific needs around `$MIRA`?

**Comment by peterjc** [comment]
This was a solution to having both MIRA 3 and 4 on the ``$PATH``, since the binary name clashes.

Probably we can fall back on using the ``$PATH`` if ``$MIRA4`` is not set.

**Comment by peterjc** [comment]
BioConda packages now cover MIRA 3.4.11, 4.0.2, 4.9.5 and 4.9.6 which is everything I have targeted with the Galaxy wrappers - see:

* https://anaconda.org/bioconda/mira/files
* https://bioconda.github.io/recipes/mira/README.html 
* https://github.com/bioconda/bioconda-recipes/tree/master/recipes/mira

**Comment by peterjc** [comment]
This should cover the ``$MIRA4`` issue by falling back on the ``$PATH`` to find mira: https://github.com/peterjc/galaxy_mira/commit/e4c56df75150c82d3e9c4ac487c4209108e52412

**Comment by peterjc** [comment]
That passed my tests on TravisCI (old packages and then switching over to conda), on the Tool Shed now as toolshed.g2.bx.psu.edu/view/peterjc/mira4_assembler v0.0.11
