### ISSUE TITLE
Missing MIRA at Galaxy

### ISSUE THREAD

**Issue by sekhwal** [peterjc/galaxy_mira#6]
Hi,
I am trying to use MIRA at Galaxy but in the Assembly panel at Galaxy, I am not seeing MIRA assembler. Please let me know how to use the assembler.
Thank you,

**Comment by peterjc** [comment]
Which Galaxy server are you using? The administrators would have to install the MIRA wrapper in order for it to appear for their users.

I would not expect a public Galaxy server to offer MIRA, as depending on the input data it can be quite resource intensive (lots of RAM).
